// AUTO-GENERATED by scripts/build.mjs — do not edit
import type { CheckMeta, CheckResult } from '../types.js';

import { meta as canvasVisualizerMeta, run as canvasVisualizerRun } from './canvas-visualizer.js';
import { meta as cdcGlobalsMeta, run as cdcGlobalsRun } from './cdc-globals.js';
import { meta as chromeRuntimeMeta, run as chromeRuntimeRun } from './chrome-runtime.js';
import { meta as chromeWindowMeta, run as chromeWindowRun } from './chrome-window.js';
import { meta as connectionRttMeta, run as connectionRttRun } from './connection-rtt.js';
import { meta as documentFocusMeta, run as documentFocusRun } from './document-focus.js';
import { meta as languagesMeta, run as languagesRun } from './languages.js';
import { meta as pdfStyleMeta, run as pdfStyleRun } from './pdf-style.js';
import { meta as playwrightGlobalsMeta, run as playwrightGlobalsRun } from './playwright-globals.js';
import { meta as pluginsMeta, run as pluginsRun } from './plugins.js';
import { meta as popupCrashMeta, run as popupCrashRun } from './popup-crash.js';
import { meta as runtimeEnabledMeta, run as runtimeEnabledRun } from './runtime-enabled.js';
import { meta as seleniumInjectionMeta, run as seleniumInjectionRun } from './selenium-injection.js';
import { meta as uaOverrideMeta, run as uaOverrideRun } from './ua-override.js';
import { meta as uaWorkerMeta, run as uaWorkerRun } from './ua-worker.js';
import { meta as visibilityStateMeta, run as visibilityStateRun } from './visibility-state.js';
import { meta as webdriverDescriptorMeta, run as webdriverDescriptorRun } from './webdriver-descriptor.js';
import { meta as webdriverTypeMeta, run as webdriverTypeRun } from './webdriver-type.js';
import { meta as webdriverMeta, run as webdriverRun } from './webdriver.js';
import { meta as webrtcLeakMeta, run as webrtcLeakRun } from './webrtc-leak.js';
import { meta as windowSizeMeta, run as windowSizeRun } from './window-size.js';

export interface BrowserCheckEntry {
  meta: CheckMeta & { runtime: 'browser' };
  run: () => CheckResult | Promise<CheckResult>;
}

export const checks: BrowserCheckEntry[] = [
  { meta: canvasVisualizerMeta, run: canvasVisualizerRun },
  { meta: cdcGlobalsMeta, run: cdcGlobalsRun },
  { meta: chromeRuntimeMeta, run: chromeRuntimeRun },
  { meta: chromeWindowMeta, run: chromeWindowRun },
  { meta: connectionRttMeta, run: connectionRttRun },
  { meta: documentFocusMeta, run: documentFocusRun },
  { meta: languagesMeta, run: languagesRun },
  { meta: pdfStyleMeta, run: pdfStyleRun },
  { meta: playwrightGlobalsMeta, run: playwrightGlobalsRun },
  { meta: pluginsMeta, run: pluginsRun },
  { meta: popupCrashMeta, run: popupCrashRun },
  { meta: runtimeEnabledMeta, run: runtimeEnabledRun },
  { meta: seleniumInjectionMeta, run: seleniumInjectionRun },
  { meta: uaOverrideMeta, run: uaOverrideRun },
  { meta: uaWorkerMeta, run: uaWorkerRun },
  { meta: visibilityStateMeta, run: visibilityStateRun },
  { meta: webdriverDescriptorMeta, run: webdriverDescriptorRun },
  { meta: webdriverTypeMeta, run: webdriverTypeRun },
  { meta: webdriverMeta, run: webdriverRun },
  { meta: webrtcLeakMeta, run: webrtcLeakRun },
  { meta: windowSizeMeta, run: windowSizeRun },
];
