#!/usr/bin/env node
/**
 * Build script for site-use.
 *
 * Steps:
 * 1. Run tsc (main compilation)
 * 2. Generate browser barrel file from checks/ directory
 * 3. Type-check browser checks with DOM lib (barrel must exist first)
 * 4. Bundle page.ts → dist/diagnose/checks.js via esbuild
 * 5. Copy index.html → dist/diagnose/index.html
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

function run(cmd, label) {
  console.log(`[build] ${label || cmd}`);
  execSync(cmd, { cwd: ROOT, stdio: 'inherit' });
}

// Step 1: Main TypeScript compilation
run('npx tsc', 'tsc (main)');

// Step 1.5: Stamp BUILD_HASH and BUILD_DATE into compiled output
try {
  const hash = execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf-8' }).trim();
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, '.');
  fs.writeFileSync(
    path.join(ROOT, 'dist', 'build-info.js'),
    `export const BUILD_HASH = '${hash}';\nexport const BUILD_DATE = '${today}';\n`,
  );
  console.log(`[build] BUILD_HASH: ${hash}`);
  console.log(`[build] BUILD_DATE: ${today}`);
} catch {
  console.log('[build] BUILD_HASH: dev (not in git repo)');
}

// Step 2: Generate browser barrel (must happen before type-check since page.ts imports it)
console.log('[build] Generating browser barrel...');
const checksDir = path.join(ROOT, 'src', 'diagnose', 'checks');
const excludePrefix = '_';
const excludeFiles = new Set(['input-trusted.ts', 'input-coords.ts', 'scroll-deltas.ts']);

const entries = fs.readdirSync(checksDir).filter((f) => {
  if (!f.endsWith('.ts')) return false;
  if (f.startsWith(excludePrefix)) return false;
  if (excludeFiles.has(f)) return false;
  return true;
});

// Detect browser checks by reading file content for runtime: 'browser'
const browserChecks = [];
for (const file of entries) {
  const content = fs.readFileSync(path.join(checksDir, file), 'utf-8');
  if (content.includes("runtime: 'browser'")) {
    browserChecks.push(file);
  }
}

const MIN_BROWSER_CHECKS = 15;
if (browserChecks.length < MIN_BROWSER_CHECKS) {
  console.error(
    `[build] ERROR: Expected >= ${MIN_BROWSER_CHECKS} browser checks, found ${browserChecks.length}: ${browserChecks.join(', ')}`,
  );
  process.exit(1);
}
console.log(`[build] Found ${browserChecks.length} browser checks`);

// Generate barrel content
const imports = [];
const checkList = [];
for (const file of browserChecks.sort()) {
  const stem = file.replace(/\.ts$/, '');
  // Convert kebab-case to camelCase for variable names
  const varName = stem.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  imports.push(
    `import { meta as ${varName}Meta, run as ${varName}Run } from './${stem}.js';`,
  );
  checkList.push(`  { meta: ${varName}Meta, run: ${varName}Run },`);
}

const barrelContent = `// AUTO-GENERATED by scripts/build.mjs — do not edit
import type { CheckMeta, CheckResult } from '../types.js';

${imports.join('\n')}

export interface BrowserCheckEntry {
  meta: CheckMeta & { runtime: 'browser' };
  run: () => CheckResult | Promise<CheckResult>;
}

export const checks: BrowserCheckEntry[] = [
${checkList.join('\n')}
];
`;

const barrelPath = path.join(checksDir, '_browser-barrel.ts');
fs.writeFileSync(barrelPath, barrelContent, 'utf-8');
console.log(`[build] Wrote ${barrelPath}`);

// Step 3: Type-check browser checks (DOM lib, no emit) — barrel must exist first
run(
  'npx tsc -p src/diagnose/tsconfig.checks.json --noEmit',
  'tsc (browser checks type-check)',
);

// Step 4: Bundle page.ts with esbuild
run(
  [
    'npx esbuild src/diagnose/page.ts',
    '--bundle',
    '--format=iife',
    '--platform=browser',
    '--target=es2022',
    '--outfile=dist/diagnose/checks.js',
  ].join(' '),
  'esbuild (bundle page.ts)',
);

// Step 5: Copy index.html
const srcHtml = path.join(ROOT, 'src', 'diagnose', 'index.html');
const distDir = path.join(ROOT, 'dist', 'diagnose');
fs.mkdirSync(distDir, { recursive: true });
fs.copyFileSync(srcHtml, path.join(distDir, 'index.html'));
console.log('[build] Copied index.html to dist/diagnose/');


console.log('[build] Done.');
